# This configuration requires Tesla V100-SXM2(32GB) x 16 GPUs It takes about 2 days.
use_amp: true
lm: transformer
lm_conf:
    pos_enc: null
    embed_unit: 128
    att_unit: 512
    head: 8
    unit: 1024
    layer: 6
    dropout_rate: 0.0

# optimization related
grad_clip: 5.0
batch_type: numel
# batch_bins: 500000000
# accum_grad: 2
# 2GPUs
# batch_bins: 100000000
# accum_grad: 10
# 1GPU
batch_bins: 50000000
accum_grad: 20
# max_epoch: 25
max_epoch: 5

optim: adam
optim_conf:
   lr: 0.005
scheduler: warmuplr
scheduler_conf:
   warmup_steps: 25000

best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 10  # 10 is good.
